# Created using Winget-CLI Testing

Id: Microsoft.PowerToys
Version: 0.27.0
Name: PowerToys
Publisher: Microsoft Corporation
License: MIT
MinOSVersion: 10.0.17134.0
Tags: FancyZones, Windows key shortcut guide, PowerRename, File Explorer, Image Resizer, Keyboard Manager, PowerToys Run, Color Picker, PowerToys, Power Toys
InstallerType: exe
Description: Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity. Inspired by the Windows 95 era PowerToys project, this reboot provides power users with ways to squeeze more efficiency out of the Windows 10 shell and customize it for individual workflows.
Homepage: https://github.com/microsoft/PowerToys
LicenseUrl: https://github.com/microsoft/PowerToys/blob/master/LICENSE
Switches:
  Silent: --silent
  SilentWithProgress: --silent
Installers:
- Arch: x64
  Url: https://github.com/microsoft/PowerToys/releases/download/v0.27.0/PowerToysSetup-0.27.0-x64.exe
  Sha256: 1D4EE633624FE6153493E30C2053DBE914423CDA18B12736D1C1467A32A6C6A2
  ProductCode: '{189FBBB3-1E68-4EE4-8D89-7BDF0F4D4E30}'
ManifestVersion: 0.1.0
